apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: react-app-namespace
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # This is for exposing it to the outside world
